### PR TITLE
Update translations + French translations

### PR DESCRIPTION
**Pull request by NathanBnm**
# Changelog

- Updated translations files
- Deleted empty `it.po`
- Added French translations to `fr.po`
- Updated `LINGUAS` (deleted `it` and added `fr`)
- Added appdata and desktop to translation files
- Added missing translations to translation files
- Fixed some errors

**This PR is ready for review**

I was able to compile and test the application and it looks like it was working.

### CODE REVIEW

**Comment by OctoD** [comment]
Thanks a lot @NathanBnm!

**Comment by NathanBnm** [comment]
Are you going to make an update soon?

**Comment by OctoD** [comment]
@NathanBnm it's in release state, we have to wait for the manual review

**Comment by NathanBnm** [comment]
But you didn't add anything to changelog in `appdata.xml`

**Comment by OctoD** [comment]
@NathanBnm 	whops, it's been a long time since I released the last version, could you please add it? I am currently working hard on something and I do not have much time right now. Thank you in advance 😃

**Comment by NathanBnm** [comment]
Yes sure

**Pull request merged**
